---
title: "Assigment 2"
output: html_notebook
---

```{r}
#install.packages("readr")  # To be able to read in swedish characters with read_delim
#install.packages("tidyverse")
```
```{r}
library(tidyverse)
library(lubridate)
library(hms)
library(readr)
```

```{r}
political_seats <- read_delim("./datasets/political_seats.csv", delim = ",", locale = locale(encoding = "ISO-8859-1"), skip = 2)
head(political_seats, show_col_types = FALSE)
```
```{r}
political_seats[political_seats==".."] <- "0"
political_seats <- type.convert(political_seats, as.is = T)

political_seats <- political_seats %>%
    pivot_longer(
        cols = -c(region, party),
        names_to = "year",
        values_to = "value"
    )
head(political_seats)
```
```{r}
political_seats <- political_seats %>% 
    pivot_wider(
        names_from = party,
        values_from = value
    )
head(political_seats)
```



```{r}
income <- read_delim("./datasets/income_statements.csv", delim = ",", locale = locale(encoding = "ISO-8859-1"), skip = 2)
income <- income[ , !(names(income) %in% "2022")]
income[income == ".."] <- "0"
income[is.na(income)] <- 0
income <- type.convert(income, as.is = T)
head(income, show_col_types = FALSE)
```

```{r}
income <- pivot_longer(income, cols= -c("region", "Income statement"), names_to ="year", values_to="values")
head(income)
```

```{r}
income <- type.convert(income, as.is = T) # convert year to int


grouped_data <- income %>%
  group_by(region, `Income statement`)

# Calculate the mean value for each four-year interval within each group
reduced_data <- grouped_data %>%
  mutate(interval = floor((year - first(year))/4) * 4 + first(year)) %>%
  group_by(region, `Income statement`, interval) %>%
  summarise(year = first(year), value = mean(values))

# Keep only the first year in each four-year interval
income <- reduced_data %>%
  group_by(region, `Income statement`) %>%
  filter(interval == year) %>%
  select(region, `Income statement`, year, value)
```
```{r}
income <- income %>% 
    pivot_wider(
        names_from = `Income statement`,
        values_from = value
    )
```

```{r}
df <- merge(income, political_seats, by=c("year", "region"))
head(df)
```

```{r}
right <- rowSums(df[, c("The Christian Democratic Party", "The Liberal Party", "The Moderate Party")])
centre <- df[["The Centre Party"]]
left <- rowSums(df[, c("The Green Party", "The Left Party", "The Social Democratic Party")])
indices <- rownames(df)
```
```{r}
majority <- character(length(right))
for (i in 1:length(right)) {
  if (indices[i] == "2018") {
    if (left[i] + centre[i] > right[i]) {
      majority[i] <- "left"
    } else if (left[i] + centre[i] < right[i]) {
      majority[i] <- "right"
    } else {
      majority[i] <- "tie"
    }
  } else {
    if (left[i] > right[i] + centre[i]) {
      majority[i] <- "left"
    } else if (left[i] < right[i] + centre[i]) {
      majority[i] <- "right"
    } else {
      majority[i] <- "tie"
    }
  }
}
```
```{r}
df$majority <- majority
head(df)
```
```{r}
df_cop <- df %>%
    group_by(majority, year) %>%
    summarize_all(mean) %>%
    ungroup()
```


```{r}
# Calling cor() on all 
(cormatrix <- df %>% select(`Financial costs`: `Total net current costs`) %>% cor)
```
```{r}
# Convert to tibble and pivot to get format for heatmap
(cortibble <- as_tibble(cormatrix, rownames = "X") %>%
    pivot_longer(
        -X,
        names_to = "Y",
        values_to = "cor"
    ))
```
```{r}
ggplot(cortibble, aes(X, Y)) +
  geom_raster(aes(X, Y, fill = cor)) +
  geom_text(aes(label = round(cor, 2)))+ 
  scale_fill_distiller(palette = "RdYlGn", limits=c(-1, 1))+
  theme(axis.text.x = element_text(angle=90, hjust=1)) 
```
```{r}
#install.packages("caret") #install caret for classification 
library(caret)
```

```{r}
# Class distribution
#percentage <- prop.table(table(df$majority)) * 100
#cbind(freq=table(df$majority), percentage=percentage)
```
```{r}
possitive_features <- c("region", "General grants and equalisation grants", "year", "Total net current costs", "Total income for operations", "Total costs for operations", "Tax revenues", "Net profit/loss for operations", "Net profit/loss after financial items", "Financial costs", "majority")

df_clean <- select(df, all_of(possitive_features))
df_clean$majority <- as.factor(df_clean$majority)
print(is.factor(df_clean$majority))
```


```{r}
# create a list of 80% of the rows in the original dataset we can use for training
test_index <- createDataPartition(df_clean$majority, p=0.80, list=FALSE)
# select 20% of the data for validation
test <- df_clean[-test_index,]
# use the remaining 80% of data to training and testing the models
df_clean <- df_clean[test_index,]
```

```{r}
library(ranger)
library(modelr)
library(tidymodels)
```

```{r}
(rf_mod <-
     rand_forest(mtry = 2, trees = 100) %>%
     set_engine("ranger", importance = "impurity") %>%
     set_mode("classification"))
```
```{r}
(rf_fit <- rf_mod %>% fit(majority~., data = df_clean))
```

```{r}
pred <- predict(rf_fit, new_data = test)
pred$.pred_class <- as.factor(pred$.pred_class)

(confmat <- confusionMatrix(pred$.pred_class, test$majority))
```
```{r}
ggplot() +
  geom_histogram(data = pred, mapping = aes(x = .pred_class, fill=.pred_class), stat="count")
```

```{r}
ggplot() +
  geom_histogram(data = test, mapping = aes(x = majority, fill=majority), stat="count")
```


















